export const tasks = [{
        id: 1,
        text: 'Finished school',
        done: false,
        createDate: new Date(2014, 9, 1, 0, 0, 0, 0),
        doneDate: null,
    },
    {
        id: 2,
        text: 'Wash car',
        done: false,
        createDate: new Date(2015, 9, 1, 0, 0, 0, 0),
        doneDate: null,
    },
    {
        id: 3,
        text: 'Learn English',
        done: false,
        createDate: new Date(2016, 9, 1, 0, 0, 0, 0),
        doneDate: null,
    },
    {
        id: 4,
        text: 'Buy laptop',
        done: true,
        createDate: new Date(2017, 9, 1, 0, 0, 0, 0),
        doneDate: new Date(2018, 7, 12),
    },
    {
        id: 5,
        text: 'Learn JavaScript',
        done: true,
        createDate: new Date(2019, 9, 1, 0, 0, 0, 0),
        doneDate: new Date(2020, 2, 5),
    },
];